#+TITLE: Horario Escolar
#+DATE:
#+LaTeX_CLASS_OPTIONS: [letterpaper, 12pt]
#+EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil title:nil num:nil
#+LATEX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{manni}
#+LATEX_HEADER:\usepackage{pdfpages}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage[top=1.4in, left=0.5in, right=0.5in, bottom=0.8in]{geometry}
#+LATEX_HEADER:\usepackage[T1]{fontenc}
#+LATEX_HEADER:\usepackage{helvet}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER:\setlength{\parindent}{0em}
#+LATEX_HEADER:\setlength{\parskip}{1em}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage {color}
#+LATEX_HEADER:\usepackage {tabularray}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor=blue,
#+LATEX_HEADER:     filecolor=magenta,
#+LATEX_HEADER:     urlcolor=cyan,
#+LATEX_HEADER:     citecolor=green,
#+LATEX_HEADER:     pdfborder={0 0 0}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[most]{tcolorbox}

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\vspace*{0.1in}

#+END_EXPORT

Date: \href{https://www.ps192.org/apps/bbmessages/show_bbm.jsp?REC_ID=139439}{February 16, 2024}

Sujeto: Horario Escolar

Un horario escolar especifica la hora de inicio y la duración de uno o más períodos de instrucción de cada día. Un horario diario consistente y rutinario
les ofrece a los niños una disciplina de trabajo durante la semana de clase. Un
horario escolar ayuda a los niños a:
- Sentirse en control de su entorno.
- Sentirse seguro, protegido y cómodo.
- Poder realizar una actividad o tarea.
- Participar en el aprendizaje.

Al igual que los adultos, los niños se sienten más confiados y seguros cuando sus
actividades diarias son predecibles y familiares.

#+begin_export latex
\tcbuselibrary{}
\newtcolorbox{bluebox}[1][]{
  colback=blue!5!white,
  colframe=blue!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=blue!50!white}
}
\newtcolorbox{greenbox}[1][]{
  colback=green!5!white,
  colframe=green!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=green!50!white}
}
\newtcolorbox{redbox}[1][]{
  colback=red!5!white,
  colframe=red!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=red!50!white}
}
#+end_export

#+begin_export latex
\begin{bluebox}[PS 192 | Horario Escolar]
\begin{table}[H]
\centering
\begin{tblr}{
  colspec={|X|X|X|X|},
  row{1}={font=\bfseries\color{MacaroniandCheese},c},
  hlines,
  vlines,
  hline{1,10} = {-}{0.08em},
}
\textbf{Periodo} & \textbf{Hora de Inicio} & \textbf{Hora de Termino} & \textbf{Duración} \\
1               & 08:00 AM                & 08:45 AM                 & 45 minutos         \\
2               & 08:45 AM                & 09:30 AM                 & 45 minutos         \\
3               & 09:30 AM                & 10:15 AM                 & 45 minutos         \\
4               & 10:15 AM                & 11:05 AM                 & 50 minutos         \\
5               & 11:05 AM                & 11:55 AM                 & 50 minutos         \\
6               & 11:55 AM                & 12:40 PM                 & 45 minutos         \\
7               & 12:40 PM                & 01:30 PM                 & 50 minutos         \\
8               & 01:30 PM                & 02:15 PM                 & 45 minutos
\end{tblr}
\end{table}
\end{bluebox}
#+end_export
