#+TITLE: Use of Electronic Devices School Policy
#+SUBTITLE: Policy regarding the use of electronic devices by students
#+AUTHOR: Hilduara Abreu
#+LaTeX_CLASS_OPTIONS: [letterpaper, 12pt]
#+EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil title:nil num:nil
#+LATEX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{manni}
#+LATEX_HEADER:\usepackage{pdfpages}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage[top=1.4in, left=0.5in, right=0.5in, bottom=0.8in]{geometry}
#+LATEX_HEADER:\usepackage[T1]{fontenc}
#+LATEX_HEADER:\usepackage{helvet}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER:\setlength{\parindent}{0em}
#+LATEX_HEADER:\setlength{\parskip}{1em}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage {color}
#+LATEX_HEADER:\usepackage {tabularray}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor=blue,
#+LATEX_HEADER:     filecolor=magenta,
#+LATEX_HEADER:     urlcolor=cyan,
#+LATEX_HEADER:     citecolor=green,
#+LATEX_HEADER:     pdfborder={0 0 0}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[most]{tcolorbox}

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\vspace*{0.01in}

#+END_EXPORT
Date: \href{https://www.ps192.org/apps/bbmessages/show_bbm.jsp?REC_ID=139439}{February 16, 2024}

Subject: \textbf{Use of Electronic Devices}

#+begin_export latex
\tcbuselibrary{}
\newtcolorbox{bluebox}[1][]{
  colback=blue!5!white,
  colframe=blue!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=blue!50!white}
}
\newtcolorbox{greenbox}[1][]{
  colback=green!5!white,
  colframe=green!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=green!50!white}
}
\newtcolorbox{redbox}[1][]{
  colback=red!5!white,
  colframe=red!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=red!50!white}
}
#+end_export
** Permitted Devices
   Although not recommended, students are allowed to bring the following electronic items to school:
   - Cell phones
   - Portable music and entertainment systems (e.g., iPods, MP3 players)

   The student and/or parent is responsible for the safety and security of these devices. The school does not provide facilities to charge devices.

** Permitted Use
   Electronic devices may be used:
   - Before 8:00 AM or after 3:35 PM in any location within the school where it
     does not disrupt educational activities.

     #+begin_export latex
\begin{bluebox}[Prohibited Use]
   Electronic devices must not:
   - Be turned on or used during instructional time, except for educational purposes with the teacher's approval.
   - Be turned on or used during quizzes, tests, or exams unless explicitly authorized or as part of an Individualized Education Program (IEP) or Section 504 Accommodation Plan.
   - Be in the possession of students during the school's bell schedule.
   - Be turned on or used during fire drills or other emergency preparedness exercises.
   - Be used in bathrooms.
   - Be used during lunch in the cafeteria or schoolyard.
   - Be used between classes in hallways and stairwells.
\end{bluebox}
#+end_export

   Use of electronic devices must comply with the DOE’s Discipline Code, school policy, Chancellor’s Regulation A-413, and the DOE’s Internet Acceptable Use and Safety Policy (IAUSP).

* Violations and Disciplinary Actions

** Violations
Violations of this policy may result in:
   - Confiscation of the device, with return only to the parent/legal guardian after a behavioral conference.
   - Revocation of the privilege to bring electronic items to school.
   - Additional disciplinary measures in accordance with the DOE Discipline Code.
