#+TITLE: PS192 | Welcome Letters Academic Year 2024-25
#+SUBTITLE: English Version
#+AUTHOR: Hilduara Abreu
#+LaTeX_CLASS_OPTIONS: [letterpaper, 12pt]
#+EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil title:nil num:nil
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usemintedstyle{manni}
#+LATEX_HEADER: \usepackage{pdfpages}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage[top=1.4in, left=0.5in, right=0.5in, bottom=0.8in]{geometry}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER: \setlength{\parindent}{0em}
#+LATEX_HEADER: \setlength{\parskip}{1em}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage {color}
#+LATEX_HEADER: \usepackage {tabularray}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor=blue,
#+LATEX_HEADER:     filecolor=magenta,
#+LATEX_HEADER:     urlcolor=cyan,
#+LATEX_HEADER:     citecolor=green,
#+LATEX_HEADER:     pdfborder={0 0 0}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[most]{tcolorbox}

#+LATEX: \includepdf[pages=1,fitpaper]{/home/rob/ps192_welcome_letters/2024/Welcome_Letters-En/welcome_letter.pdf}

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\newpage
#+END_EXPORT
\vspace*{-0.5cm}

* Table of Contents
  - [[#introduction][Introduction]]
  - [[#bell-schedule][Bell Schedule]]
  - [[#use-of-electronic-devices][Use of Electronic Devices]]
  - [[#violations-and-disciplinary-actions][Violations and Disciplinary Actions]]
  - [[#welcome-letter-3-k-and-pre-k][Welcome Letter 3-K and Pre-K]]
  - [[#welcome-letter-k-5-2024][Welcome Letter Grades K-5]]
  - [[#promotional-criteria-and-grading-policy][Promotional Criteria and Grading Policy]]
#+begin_export latex
\newpage
#+end_export
\vspace*{-0.5cm}

#+begin_export latex
\tcbuselibrary{}
\newtcolorbox{bluebox}[1][]{
  colback=blue!5!white,
  colframe=blue!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=blue!50!white}
}
\newtcolorbox{greenbox}[1][]{
  colback=green!5!white,
  colframe=green!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=green!50!white}
}
\newtcolorbox{redbox}[1][]{
  colback=red!5!white,
  colframe=red!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=red!50!white}
}
#+end_export

* Introduction
:PROPERTIES:
:ID: introduction
:END:

Dear Parents and School Community,

Welcome to PS 192! We are committed to providing a safe and nurturing environment where every student can thrive academically, socially, and emotionally. As we embark on another exciting school year, it is essential for all members of our school community to stay informed about our policies, rules, events, and core values. These guidelines help us create a positive and productive learning atmosphere for our students.

#+BEGIN_QUOTE
 "Education is the journey where Justice, Honor, and Self-Discipline guide us to
 unlock our fullest potential. At PS 192, we believe in cultivating these core
 values to inspire greatness in every student, parent, and teacher, setting the
 foundation for a brighter future. Together, let's embark on this new academic
 year with a shared commitment to excellence and a passion for lifelong
 learning."   -- Hilduara Abreu
#+END_QUOTE

At PS 192, we believe in the power of education to transform lives. Our dedicated staff works tirelessly to offer the highest quality education, empowering our students to become the next generation of thinkers and leaders who will make a positive impact on our city and beyond. Your partnership and support are crucial in this journey, and we thank you for being an integral part of our community.

Together, we can ensure that PS 192 continues to be a place where every child feels valued and inspired to reach their full potential. We look forward to a successful and enriching school year with your continued involvement and cooperation.
With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The school of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.5cm}

** Bell Schedule
:PROPERTIES:
:ID: bell-schedule
:END:

A bell schedule specifies the start time and duration of one or more instructional periods on each day of a day pattern. A consistent daily schedule and step-by-step routines give children a predictable day. A Bell Schedule helps children:
- Feel in control of their environment
- Feel safe, secure, and comfortable
- Know what is happening now and what comes next
- Know how to do an activity or task
- Engage in learning

Just like adults, children feel more confident and secure when their daily activities are predictable and familiar.

#+begin_export latex
\begin{bluebox}[PS 192 | Bell Schedule]
\begin{table}[H]
\centering
\begin{tblr}{
  colspec={|X|X|X|X|},
  row{1}={font=\bfseries\color{MacaroniandCheese},c},
  hlines,
  vlines,
  hline{1,10} = {-}{0.08em},
}
\textbf{Period} & \textbf{Start Time} & \textbf{End Time} & \textbf{Length} \\
1               & 08:00 AM            & 08:45 AM          & 45 minutes      \\
2               & 08:45 AM            & 09:30 AM          & 45 minutes      \\
3               & 09:30 AM            & 10:15 AM          & 45 minutes      \\
4               & 10:15 AM            & 11:05 AM          & 50 minutes      \\
5               & 11:05 AM            & 11:55 AM          & 50 minutes      \\
6               & 11:55 AM            & 12:40 PM          & 45 minutes      \\
7               & 12:40 PM            & 01:30 PM          & 50 minutes      \\
8               & 01:30 PM            & 02:15 PM          & 45 minutes
\end{tblr}
\end{table}
\end{bluebox}
#+end_export

#+begin_export latex
\pagebreak
#+end_export
\vspace*{0.5cm}

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The school of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}

#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.5cm}

** Use of Electronic Devices
:PROPERTIES:
:ID: use-of-electronic-devices
:END:

#+begin_export latex
\begin{redbox}[PS 192 | Policy]
Prohibited Devices
Although not recommended, students are allowed to bring the following electronic items to school:
\begin{itemize}
\item Cell phones
\item Portable music and entertainment systems (e.g., iPods, MP3 players)
\end{itemize}
\textit{The student and/or parent is responsible for the safety and security of these devices. The school does not provide facilities to charge devices.}
\vspace*{3mm}

Important Key Points:
\begin{itemize}
\item Before 8:00 AM or after 3:35 PM in any location within the school where it does not disrupt educational activities.
\item Be turned on or used during instructional time, except for educational purposes with the teacher's approval.
\item Be turned on or used during quizzes, tests, or exams unless explicitly authorized or as part of an Individualized Education Program (IEP) or Section 504 Accommodation Plan.
\item Be in the possession of students during the school's bell schedule.
\item Be turned on or used during fire drills or other emergency preparedness exercises.
\item Be used in bathrooms.
\item Be used during lunch in the cafeteria or schoolyard.
\item Be used between classes in hallways and stairwells.
\end{itemize}
\end{redbox}
#+end_export

Use of electronic devices must comply with the DOE’s Discipline Code, school policy, Chancellor’s Regulation A-413, and the DOE’s Internet Acceptable Use and Safety Policy (IAUSP).
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.2cm}

** Violations and Disciplinary Actions
:PROPERTIES:
:ID: violations-and-disciplinary-actions
:END:

Violations of this policy may result in:
- Confiscation of the device, with return only to the parent/legal guardian after a behavioral conference.
- Revocation of the privilege to bring electronic items to school.
- Additional disciplinary measures in accordance with the DOE Discipline Code.

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The school of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-1cm}

** Welcome Letter 3-K and Pre-K
:PROPERTIES:
:ID: welcome-letter-3-k-and-pre-k
:END:

We're excitedly counting down the days until the arrival of our students on Thursday, September 5th, 2024! Our dedicated instructors and school staff are eagerly looking forward to welcoming you to what promises to be a thrilling year of fostering connections and building a strong community. Our caring educators are excited to share their laughter, energy, and passion for learning with your children.

As we gear up for your child's return, we want to share important information in place at P.S. 192 to ensure a safe and enjoyable learning experience for everyone. Please take note of the following guidelines:
#+begin_export latex
\begin{redbox}[PS 192 | Key Points to Enhance Learning!]
\begin{itemize}
\item Uniforms: All students are required to come to school daily dressed in their uniforms, which remain the same: a burgundy shirt and navy bottoms (pants, skirt, jumper).
\item Arrival and Dismissal: To ensure a safe and efficient arrival and dismissal process, please take note of the following schedule. There will be staff members and signs pointing families to where to go during the first week of school.
  \begin{itemize}
  \item Arrival: Backyard at 8:00 AM
  \item Dismissal: Backyard at 2:15 PM
  \end{itemize}
\item First Days of School: While all students will have a school day from 8:00-2:20 PM each day, parents are invited to remain with their children on Thursday and Friday from 8:00-10:00 AM to help our young scholars transition smoothly into the school environment.
\item School Supplies: P.S. 192 will be providing all basic school supplies, such as notebooks, folders, and crayons. We only ask that 3K and PreK families provide a backpack, change of clothing, and supplies for their daily nap time (blanket, sheet, and/or small transitional object like a doll or stuffed animal).
\end{itemize}
\end{redbox}
#+end_export
We feel privileged to be part of a community where parents, teachers, staff, and students work together to build strong relationships that support academic and social growth. We are eagerly looking forward to your participation in the various events throughout the school year and welcome your active involvement in your child's educational journey.

Regular updates regarding school-wide events will be communicated through Our Website: \href{https://www.ps192.org}{www.ps192.org}, \href{https://www.classdojo.com/}{ClassDojo}, School Messenger, and our WhatsApp group. Should you have any questions, please do not hesitate to contact our Parent Coordinator, Angela Rijo, at \href{mailto:arijo@schools.nyc.gov}{arijo@schools.nyc.gov}, school website: \href{https://www.ps192.org/angela}{www.ps192.org/angela}, or (212) 775-9560.
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.1cm}
We will be hosting events throughout the year and look forward to partnering with you both in person and virtually. Please stay tuned for more information on all of our upcoming events:
- On September 12th, we will be hosting Evening Parent-Teacher Conferences.

We're thrilled to kick-start this school year and engage with you to ensure your child enjoys the best possible learning experience—one where they feel valued, encouraged, and excited about learning and its limitless possibilities.

I am deeply honored to serve as the principal of PS 192. Thank you for your unwavering cooperation and dedication to our students, faculty, and staff. I eagerly look forward to collaborating with you in your child's educational journey.

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The school of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-1cm}

** Welcome Letter Grades K-5
:PROPERTIES:
:ID: welcome-letter-k-5-2024
:END:

As we approach the commencement of the new school year for 2024-25, commencing
on September 7th, we extend a warm welcome to all our students. We trust that
you have had a pleasant and healthy summer break. Our devoted and compassionate
team of educators and school personnel eagerly anticipates your return for what
promises to be a year filled with excitement, laughter, and learning.
#+begin_export latex
\begin{greenbox}[PS 192 | Key Points to Enhance Learning!]
\begin{itemize}
\item Uniforms: All students are required to come to school daily dressed in their uniforms, which remain the same: a burgundy shirt and navy bottoms (pants, skirt, jumper).
\item Arrival and Dismissal: To ensure a safe and efficient arrival and dismissal process, please take note of the following schedule. There will be staff members and signs pointing families to where to go during the first week of school.
\item Arrival: New this year, ALL students in Grades K-5 will enter through the Cafeteria each morning, beginning at 7:40 AM to eat breakfast.
\item Dismissal: New this year, ALL students in Grades K-5 will be dismissed from the backyard at 2:15 PM. There will be designated spots for each class by grade. Please follow the signs.
\item School Supplies: PS 192 will be providing all basic school supplies, such as notebooks, folders, and crayons. We only ask that families in Grades K-5 provide students with a backpack and one box of Ziplock gallon-size bags for students to use for centers, book baggies, and math tool kits.
\end{itemize}
\end{greenbox}
#+end_export
*** Community and Events
We feel privileged to be part of a community where parents, teachers, staff, and students work together to build strong relationships that support academic and social growth. We are eagerly looking forward to your participation in the various events throughout the school year and welcome your active involvement in your child’s educational journey. It is an honor to be part of a community where parents, teachers, staff, and students collectively strive to foster strong relationships that promote academic and social growth. We eagerly anticipate your participation in the events scheduled throughout the school year and value your active engagement in your child’s education.

Regular updates regarding your child’s school-wide events will be communicated through Our Website: [[http://www.ps192.org][www.ps192.org]], ClassDojo, School Messenger, and our WhatsApp group. Should you have any questions, please do not hesitate to contact our Parent Coordinator, Angela Rijo, at [[http://www.ps192.org/angela][www.ps192.org/angela]], or (212) 775-9560.
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.5cm}

We will be hosting events throughout the year and look forward to partnering with you both in person and virtually. Please stay tuned for more information on all of our upcoming events:

*Upcoming Event*
- On September 12, we will be hosting our Evening Parent-Teacher Conferences

We are eagerly counting down the days until we can welcome you back on Thursday, September 5th. I am honored to serve as the principal of PS 192, and I extend my heartfelt gratitude for your cooperation and dedication to the well-being of our children, staff, and school.

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The school of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-1cm}

** Promotional Criteria and Grading Policy
:PROPERTIES:
:ID: promotional-criteria-and-grading-policy
:END:

Chancellor Regulation A-501 implements a system-wide promotion policy with
clearly defined standards for promotion for each grade. The P.S. 192 Promotional Criteria Policy provides the process and procedures
for the implementation of this promotion policy. This policy is effective as of September 5th, 2024.

This policy is being promulgated in the context of the following goals established by the Chancellor’s
Regulation A-501:

All students in Kindergarten through grade 5 will meet or exceed rigorous academic standards in a performance-based core curriculum. In grades 3 through 5, all students will meet or exceed the promotion standards referred to in this regulation, and set forth in DOE issued guidance, in order to be promoted to the next grade and, ultimately, to be prepared for college and careers.

- The entire school community will be engaged continuously in creating and supporting effective strategies for improved student achievement.
- A comprehensive student assessment system, aligned with established State and City performance standards, will be used on an ongoing basis to measure student progress and to improve classroom instruction.

#+begin_export latex
\begin{redbox}[Classwork Grading System]
\begin{table}[H]
\centering
\begin{tblr}{
  colspec={|X|X|},
  row{1}={font=\bfseries\color{MacaroniandCheese},c},
  hlines,
  vlines,
  hline{1,6} = {-}{0.08em},
}
\textbf{Component}              & \textbf{Weight} \\
In-House Assessments            & 50\%            \\
Daily Classwork                 & 30\%            \\
Classroom Participation         & 10\%            \\
Projects                        & 5\%             \\
Homework                        & 5\%             \\
\end{tblr}
\end{table}
\end{redbox}
#+end_export

*Promotional Criteria for Grades K-2*
- 95 percent Attendance
#+begin_export latex
\pagebreak
\vspace*{-1cm}
#+end_export
- Meet Performance Standards in ALL Core Subjects: ELA, Math, S.S., and Science. This means to
  obtain a Performance Level 2 (a numeric score of 65 percent) in all core subject areas: Reading,
  Writing, Mathematics, Science, and Social Studies. The average of the quizzes and unit exams will
  be used to determine the overall grade:
  - Level 1: An aggregate average score of 0-64 points
  - Level 2: An aggregate average score of 65-79 points
  - Level 3: An aggregate average score of 80-89 points
  - Level 4: An aggregate average score of 90-100 points

*Reading: Meet Minimum Grade Specific DRA Reading Benchmark*
- Kindergarten: Benchmark Reading Level 6 (E)
- First Grade: Benchmark Reading Level 15-16 (L)
- Second Grade: Benchmark Reading Level 18 (J)

*Writing: Obtain a cumulative Level 2 performance rating in the Writing Portfolio*
- Kindergarten: 4 Writing Pieces (2 fiction and 2 non-fiction)
- First grade: 4 Writing Performance Tasks (2 fiction and 2 non-fiction)
- Second grade: 4 Writing Performance Tasks (2 fiction and 2 non-fiction)

*Math: Obtain a cumulative Level 2 performance rating. The average of the quizzes and unit exams will be used to determine the overall grade.*
- Level 1: An aggregate average score of 0-64 points
- Level 2: An aggregate average score of 65-79 points
- Level 3: An aggregate average score of 80-89 points
- Level 4: An aggregate average score of 90-100 points

*Project Assignments: Obtain a cumulative Level 2 performance rating in each project.*
- Kindergarten: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)
#+begin_export latex
\pagebreak
\vspace*{-1cm}
#+end_export
- First grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)
- Second grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)

*Teacher’s Recommendation*
- Holistic analysis and evidence of classwork

*Promotional Criteria for Grades 3-5*
- 95 percent Attendance
- Meet Performance Standards in ALL Core Subjects: ELA, Math, S.S., and Science. This means to obtain a Performance Level 2 (a numeric score of 65 percent) in all core subject areas: Reading, Writing,

*Mathematics, Science, and Social Studies. The average of the quizzes and unit exams will be used to determine the overall grade:*
  - Level 1: An aggregate average of 0-64 points
  - Level 2: An aggregate average of 65-79 points
  - Level 3: An aggregate average of 80-89 points
  - Level 4: An aggregate average of 90-100 points

*Reading: Meet Minimum Grade Specific DRA Reading Benchmark*
- Third Grade: Benchmark Reading Level 34-38 (M-N)
- Fourth Grade: Benchmark Reading Level 38-40 (O-P)
- Fifth Grade: Benchmark Reading Level 50 (Q-R)

*Writing: Obtain a cumulative Level 2 performance rating in the Writing Portfolio*
- Third Grade: 4 Writing Pieces (2 fiction and 2 non-fiction)
- Fourth Grade: 4 Writing Performance Tasks (1 fiction and 3 non-fiction)
- Fifth Grade: 4 Writing Performance Tasks (1 fiction and 3 non-fiction)
#+begin_export latex
\pagebreak
\vspace*{-0.5cm}
#+end_export
*Math: Obtain a cumulative Level 2 performance rating. The average of the quizzes and unit exams will be used to determine the overall grade.*
- Level 1: An aggregate average score of 0-64 points
- Level 2: An aggregate average score of 65-79 points
- Level 3: An aggregate average score of 80-89 points
- Level 4: An aggregate average score of 90-100 points

*Project Assignments: Obtain a cumulative Level 2 performance rating in each project.*
- Third Grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)
- Fourth Grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)
- Fifth Grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)

*Teacher's Recommendation*
- Holistic analysis and evidence of classwork

*Promotional Criteria for English Language Learners*

English Language Learners will be held to promotional standards based on the
number of years in NYC Public Schools:
- 1st year ELLs and SIFEs
  - Meet benchmarks in specific subject areas such as Math, S.S., and Science in
    their native language.
- 2nd and 3rd year ELLs
  - Score a level 2 in the NYS Math Assessment and make expected gains in the NYSESLAT (51 points within a proficiency level)
  - Score at least a score of 65 percent (Performance Level 2) in a minimum of
    three core subject areas.
#+begin_export latex
\pagebreak
\vspace*{-1cm}
#+end_export
- 4th year ELLs will be held to the same standards as English Language Proficient Students.

*Promotional Criteria for Special Education Students*
- Special Education students will be held to the promotion standards stated in the student’s IEP.
- A student whose IEP does not specify modified promotion criteria will be held to the same standard promotional criteria as General Education Students.
- Teachers will use all available assessments: standardized tests, performance tasks, ongoing assessments of student work, conference notes, teacher observations, and professional judgment – as a mechanism to improve classroom instruction and to provide parents with detailed information about their child’s academic progress.

All promotional criteria are subject to the Principal’s final approval. Parents will also be involved in the decision-making process. Teachers will maintain collections of students' work and formative and summative data that document students' progress toward meeting performance standards and benchmarks. Teachers will be meeting with parents regularly for:
- Our staff shall employ various communication methods to ensure parents and guardians are consistently informed about their child’s social-emotional and academic development.
  - Zoom or Google virtual conferences
  - Phone conversations
  - Written communication, which includes ClassDojo, email, and text messages, will be utilized to inform parents.

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

\textbf{Hilduara Abreu}, \textbf{Principal}

\textit{The School of Joyful Learning!}

[[https://www.ps192.org][www.ps192.org]]
