#+TITLE: Use of Electronic Devices School Policy
#+SUBTITLE: Policy regarding the use of electronic devices by students
#+AUTHOR: Hilduara Abreu
#+LaTeX_CLASS_OPTIONS: [letterpaper, 12pt]
#+EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil title:nil num:nil
#+LATEX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{manni}
#+LATEX_HEADER:\usepackage{pdfpages}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage[top=1.4in, left=0.5in, right=0.5in, bottom=0.8in]{geometry}
#+LATEX_HEADER:\usepackage[T1]{fontenc}
#+LATEX_HEADER:\usepackage{helvet}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER:\setlength{\parindent}{0em}
#+LATEX_HEADER:\setlength{\parskip}{1em}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage {color}
#+LATEX_HEADER:\usepackage {tabularray}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor=blue,
#+LATEX_HEADER:     filecolor=magenta,
#+LATEX_HEADER:     urlcolor=cyan,
#+LATEX_HEADER:     citecolor=green,
#+LATEX_HEADER:     pdfborder={0 0 0}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[most]{tcolorbox}

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\vspace*{0.01in}


#+END_EXPORT
#+begin_export latex
\tcbuselibrary{}
\newtcolorbox{bluebox}[1][]{
  colback=blue!5!white,
  colframe=blue!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=blue!50!white}
}
\newtcolorbox{greenbox}[1][]{
  colback=green!5!white,
  colframe=green!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=green!50!white}
}
\newtcolorbox{redbox}[1][]{
  colback=red!5!white,
  colframe=red!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=red!50!white}
}
#+end_export

* Table of Contents
  1. [[#introduction][Introduction]]
  2. [[#english-version][English Version]]
  3. [[#versin-en-espaol][Versión en Español]]
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-1cm}

* Introduction
:PROPERTIES:
:ID: introduction
:END:

Dear Parents and School Community,

Welcome to PS 192! We are committed to providing a safe and nurturing environment where every student can thrive academically, socially, and emotionally. As we embark on another exciting school year, it is essential for all members of our school community to stay informed about our policies, rules, events, and core values. These guidelines help us create a positive and productive learning atmosphere for our students.

At PS 192, we believe in the power of education to transform lives. Our dedicated staff works tirelessly to offer the highest quality education, empowering our students to become the next generation of thinkers and leaders who will make a positive impact on our city and beyond. Your partnership and support are crucial in this journey, and we thank you for being an integral part of our community.

Together, we can ensure that PS 192 continues to be a place where every child feels valued and inspired to reach their full potential. We look forward to a successful and enriching school year with your continued involvement and cooperation.

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The school of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-1cm}

* English Version
:PROPERTIES:
:ID: english-version
:END:

Date: \href{https://www.ps192.org}{September 5th, 2024}

Subject: *Use of Electronic Devices*

#+begin_export latex
\begin{redbox}[PS 192 | Policy]
Prohibited Devices
Although not recommended, students are allowed to bring the following electronic items to school:
\begin{itemize}
\item Cell phones
\item Portable music and entertainment systems (e.g., iPods, MP3 players)
\end{itemize}
\textit{The student and/or parent is responsible for the safety and security of these devices. The school does not provide facilities to charge devices.}
\vspace*{3mm}

Important Key Points:
\begin{itemize}
\item Before 8:00 AM or after 3:35 PM in any location within the school where it does not disrupt educational activities.
\item Be turned on or used during instructional time, except for educational purposes with the teacher's approval.
\item Be turned on or used during quizzes, tests, or exams unless explicitly authorized or as part of an Individualized Education Program (IEP) or Section 504 Accommodation Plan.
\item Be in the possession of students during the school's bell schedule.
\item Be turned on or used during fire drills or other emergency preparedness exercises.
\item Be used in bathrooms.
\item Be used during lunch in the cafeteria or schoolyard.
\item Be used between classes in hallways and stairwells.
\end{itemize}
\end{redbox}
#+end_export

Use of electronic devices must comply with the DOE’s Discipline Code, school policy, Chancellor’s Regulation A-413, and the DOE’s Internet Acceptable Use and Safety Policy (IAUSP).
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.5cm}

**Violations and Disciplinary Actions**

Violations of this policy may result in:
- Confiscation of the device, with return only to the parent/legal guardian after a behavioral conference.
- Revocation of the privilege to bring electronic items to school.
- Additional disciplinary measures in accordance with the DOE Discipline Code.

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The school of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-1cm}

* Versión en Español
:PROPERTIES:
:ID: versin-en-espaol
:END:

Fecha: \href{https://www.ps192.org}{5 de septiembre de 2024}

Asunto: *Uso de Dispositivos Electrónicos*

#+begin_export latex
\begin{greenbox}[PS 192 | Política]
Dispositivos Prohibidos
Aunque no se recomienda, se permite a los estudiantes traer los siguientes artículos electrónicos a la escuela:
\begin{itemize}
\item Teléfonos móviles
\item Sistemas portátiles de música y entretenimiento (por ejemplo, iPods, reproductores MP3)
\end{itemize}
\textit{El estudiante y/o los padres son responsables de la seguridad de estos dispositivos. La escuela no proporciona instalaciones para cargar dispositivos.}
\vspace*{3mm}

Puntos Clave Importantes:
\begin{itemize}
\item Antes de las 8:00 AM o después de las 3:35 PM en cualquier lugar dentro de la escuela donde no interrumpa las actividades educativas.
\item Encenderse o utilizarse durante el tiempo de instrucción, excepto para fines educativos con la aprobación del maestro.
\item Encenderse o utilizarse durante exámenes, pruebas o evaluaciones, a menos que esté explícitamente autorizado o como parte de un Programa de Educación Individualizado (IEP) o Plan de Acomodación de la Sección 504.
\item Estar en posesión de los estudiantes durante el horario de timbre de la escuela.
\item Encenderse o utilizarse durante simulacros de incendio u otros ejercicios de preparación para emergencias.
\item Utilizarse en los baños.
\item Utilizarse durante el almuerzo en la cafetería o el patio escolar.
\item Utilizarse entre clases en los pasillos y escaleras.
\end{itemize}
\end{greenbox}
#+end_export

El uso de dispositivos electrónicos debe cumplir con el Código de Disciplina del DOE, la política escolar, el Reglamento del Canciller A-413 y la Política de Uso Aceptable de Internet y Seguridad del DOE (IAUSP).
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.5cm}

**Violaciones y Acciones Disciplinarias**

Las violaciones de esta política pueden resultar en:
- Confiscación del dispositivo, con devolución solo al padre/tutor legal después de una conferencia de comportamiento.
- Revocación del privilegio de traer artículos electrónicos a la escuela.
- Medidas disciplinarias adicionales de acuerdo con el Código de Disciplina del DOE.

Con Justicia, Honor y Autodisciplina,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Directora*

*¡La escuela del Aprendizaje Alegre!*

\href{www.ps192.org}{www.ps192.org}
