#+TITLE: School Year 2024-25 | Principal Message January 2025
#+AUTHOR: Hilduara Abreu
#+EMAIL: ps192@ps192.org
#+LaTeX_CLASS_OPTIONS: [letterpaper, 14pt]
#+EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil title:nil num:nil
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usemintedstyle{manni}
#+LATEX_HEADER: \usepackage{pdfpages}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage[top=1.4in, left=0.5in, right=0.5in, bottom=0.8in]{geometry}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER: \setlength{\parindent}{0em}
#+LATEX_HEADER: \setlength{\parskip}{1em}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage {color}
#+LATEX_HEADER: \usepackage {tabularray}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor=blue,
#+LATEX_HEADER:     filecolor=magenta,
#+LATEX_HEADER:     urlcolor=cyan,
#+LATEX_HEADER:     citecolor=green,
#+LATEX_HEADER:     pdfborder={0 0 0}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[most]{tcolorbox}

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\newpage
#+END_EXPORT
\vspace*{0.5cm}
/*Subject: Welcome to February, 2025 at PS 192: The School of Joyful Learning!*/

Dear PS192 Families,

I hope this letter finds you well and staying warm as we move through February! This month brings with it a sense of love, connection, and a well-deserved break for our students.

As we celebrate Valentine’s Day, let’s take a moment to appreciate the kindness and friendships that make our school community so special. Shortly after, we’ll have our Mid-Winter Recess from February 17th to February 21st. This is a wonderful opportunity for families to enjoy quality time together. If you’re looking for ways to keep your children engaged, I encourage you to explore the city’s incredible museums, visit the Public Library for events or some cozy reading time, or take advantage of the library’s many online resources.

At PS 192, we have a full schedule both before and after the break. Here are some important dates to keep in mind:

- 📌 3K, Pre-K, Kindergarten, and Middle School Applications for the 2025-2026 school year are due
- 📌 Coffee with the Principal & Parent Association Meeting + Valentine’s Day Celebration – February 14th, 8:00 AM in the Gym
- 📌 Graduation Meeting – February 27th
  - Pre-K & Kindergarten: 2:30 PM - 3:00 PM
  - 5th Grade: 3:20 PM - 4:00 PM (Library)

I hope you all have a restful and joyful Mid-Winter Recess filled with love and laughter. Happy Valentine’s Day!

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The School of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}

\newpage

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\newpage
#+END_EXPORT
\vspace*{0.1cm}
/*Asunto: Bienvenidos a febrero de 2025 en PS 192: ¡La Escuela del Aprendizaje Alegre!*/

*Estimados padres y tutores*,

*Espero que esta carta los encuentre bien y abrigados mientras avanzamos en febrero.* ¡Este mes trae consigo un sentido de amor, conexión y un merecido descanso para nuestros estudiantes!

Al celebrar el *Día de San Valentín*, tomémonos un momento para apreciar la bondad y las amistades que hacen que nuestra comunidad escolar sea tan especial. Poco después, tendremos nuestro *Receso de Invierno* del *17 al 21 de febrero*. Esta es una maravillosa oportunidad para que las familias disfruten de tiempo de calidad juntas. Si buscan actividades para mantener a sus hijos comprometidos, los animo a explorar los increíbles **museos de la ciudad**, visitar la **Biblioteca Pública** para eventos o un rato acogedor de lectura, o aprovechar los muchos **recursos en línea** de la biblioteca.

En *PS 192*, tenemos un calendario lleno tanto antes como después del receso. Aquí hay algunas fechas importantes para recordar:

 - 📌 *Fecha límite para las solicitudes de 3K, Pre-K, Kindergarten y Secundaria para el año escolar 2025-2026*
 - 📌 *Café con la Directora y Reunión de la Asociación de Padres + Celebración del Día de San Valentín* – *14 de febrero, 8:00 AM en el gimnasio*
 - 📌 *Reunión de Graduación – 27 de febrero*

        🔹 *Pre-K y Kindergarten:* 2:30 PM - 3:00 PM
        🔹 *5 grado:* 3:20 PM - 4:00 PM (Biblioteca)

Espero que todos tengan un *receso de invierno relajante y lleno de amor y alegría*. ¡*Feliz Día de San Valentín!* 💖🎉

Con justicia, honor y autodisciplina,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

La escuela del aprendizaje allegro!

\href{www.ps192.org}{www.ps192.org}
