#+TITLE: School Uniform Policy
#+SUBTITLE: Policy regarding the use of uniforms by students
#+AUTHOR: Hilduara Abreu
#+LaTeX_CLASS_OPTIONS: [letterpaper, 12pt]
#+EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil title:nil num:nil
#+LATEX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{manni}
#+LATEX_HEADER:\usepackage{pdfpages}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage[top=1.4in, left=0.5in, right=0.5in, bottom=0.8in]{geometry}
#+LATEX_HEADER:\usepackage[T1]{fontenc}
#+LATEX_HEADER:\usepackage{helvet}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER:\setlength{\parindent}{0em}
#+LATEX_HEADER:\setlength{\parskip}{1em}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage {color}
#+LATEX_HEADER:\usepackage {tabularray}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor=blue,
#+LATEX_HEADER:     filecolor=magenta,
#+LATEX_HEADER:     urlcolor=cyan,
#+LATEX_HEADER:     citecolor=green,
#+LATEX_HEADER:     pdfborder={0 0 0}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[most]{tcolorbox}

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\vspace*{-0.2in}


#+END_EXPORT
#+begin_export latex
\tcbuselibrary{}
\newtcolorbox{bluebox}[1][]{
  colback=blue!5!white,
  colframe=blue!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=blue!50!white}
}
\newtcolorbox{greenbox}[1][]{
  colback=green!5!white,
  colframe=green!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=green!50!white}
}
\newtcolorbox{redbox}[1][]{
  colback=red!5!white,
  colframe=red!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=red!50!white}
}
#+end_export

* School Uniform Policy
  1. [[#english-version][English Version]]
  2. [[#version-en-espanol][Versión en Español]]
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.8cm}

* English Version
:PROPERTIES:
:ID: english-version
:END:

**Uniform Details**

1. *Burgundy Shirt*: All students are required to wear a burgundy-colored shirt as the upper part of their uniform.
2. *Navy Pants*: Navy blue pants or trousers are to be worn as the lower part of the uniform.

The uniform policy will be enforced during school hours and at all school-related events and activities, such as field trips and special assemblies.

**Benefits of the Uniform Policy**

Uniforms serve as a unifying element within our school community and offer several significant advantages:

1. *Promoting Equality*: Uniforms eliminate socioeconomic disparities among students, ensuring that everyone is dressed the same way, regardless of their family’s financial circumstances.
2. *Enhancing Focus*: Wearing uniforms reduces distractions related to fashion and peer pressure, allowing students to concentrate on their studies and personal growth.
3. *Fostering School Pride*: A uniform instills a sense of pride and belonging among students, helping them identify with and appreciate their school community.
4. *Improving Safety*: Uniforms make it easier to identify intruders on school premises, enhancing overall security.
5. *Preparing for Future Success*: Encouraging a dress code similar to professional attire helps prepare students for future careers where a professional appearance is important.

**Dress Down Days**

We understand that personal expression is important, and therefore, "Dress Down Days" will be occasionally scheduled throughout the school year, allowing students to express their individuality through clothing choices. We kindly request your cooperation and support in ensuring that your child arrives at school dressed in accordance with our uniform policy. We believe that this will contribute to a more positive and productive learning environment for all students.
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.5cm}

**Contact Information**

Should you have any questions or concerns regarding the uniform policy, please feel free to reach out to our Parent Coordinator, Ms. Angela Rijo, via the following channels:
- Website: [[https://www.ps192.org/angela]]
- Whatsapp Group
- ClassDojo
- Phone: (212) 775-9560
- In person during office hours: 9:00 AM - 3:00 PM

We are here to assist and support you.

**Closing**

Thank you for your partnership in nurturing a strong and vibrant learning community at P.S. 192. We look forward to a successful and enriching academic year ahead.

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The School of Joyful Learning!*

\href{https://www.ps192.org}{www.ps192.org}

#+begin_export latex
\pagebreak
#+end_export
\vspace*{-1cm}

* Versión en Español
:PROPERTIES:
:ID: version-en-espanol
:END:

**Detalles del Uniforme**

1. *Camisa Color Vino*: Se requiere que todos los estudiantes usen una camisa de color borgoña como la parte superior de su uniforme.
2. *Pantalones Azul Marino*: Pantalones o pantalones de color azul marino deben ser usados como la parte inferior del uniforme.

La política de uniformes se aplicará durante el horario escolar y en todos los eventos y actividades relacionadas con la escuela, como excursiones y asambleas especiales.

**Beneficios de la Política de Uniformes**

Los uniformes sirven como un elemento unificador dentro de nuestra comunidad escolar y ofrecen varias ventajas significativas:

1. *Promoción de la Igualdad*: Los uniformes eliminan las disparidades socioeconómicas entre los estudiantes, asegurando que todos se vistan de la misma manera, independientemente de las circunstancias financieras de sus familias.
2. *Mejorando la Concentración*: Usar uniformes reduce las distracciones relacionadas con la moda y la presión de grupo, lo que permite a los estudiantes concentrarse en sus estudios y crecimiento personal.
3. *Fomento del Orgullo Escolar*: Un uniforme infunde un sentido de orgullo y pertenencia entre los estudiantes, ayudándolos a identificarse y apreciar su comunidad escolar.
4. *Mejora de la Seguridad*: Los uniformes hacen que sea más fácil identificar intrusos en las instalaciones escolares, mejorando la seguridad general.
5. *Preparación para el Éxito Futuro*: Fomentar un código de vestimenta similar a la vestimenta profesional ayuda a preparar a los estudiantes para futuras carreras donde una apariencia profesional es importante.

**Días de Ropa Libre**
#+begin_export latex
\pagebreak
#+end_export
\vspace*{-0.5cm}

Entendemos que la expresión personal es importante, y por lo tanto, los "Días de Ropa Libre" se programarán ocasionalmente a lo largo del año escolar, permitiendo a los estudiantes expresar su individualidad a través de sus elecciones de vestimenta. Solicitamos amablemente su cooperación y apoyo para asegurarse de que su hijo llegue a la escuela vestido de acuerdo con nuestra política de uniformes. Creemos que esto contribuirá a un ambiente de aprendizaje más positivo y productivo para todos los estudiantes.

**Información de Contacto**

Si tiene alguna pregunta o inquietud con respecto a la política de uniformes, no dude en ponerse en contacto con nuestra Coordinadora de Padres, Sra. Angela Rijo, a través de los siguientes canales:
- Sitio web: [[https://www.ps192.org/angela]]
- Grupo de Whatsapp
- ClassDojo
- Teléfono: (212) 775-9560
- En persona durante el horario de oficina: 9:00 AM - 3:00 PM

Estamos aquí para ayudar y apoyarlos.

**Conclusión**

Gracias por su colaboración en el fomento de una comunidad de aprendizaje fuerte y vibrante en P.S. 192. Esperamos un año académico exitoso y enriquecedor.

Con Justicia, Honor y Autodisciplina,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Directora*

*¡La escuela del Aprendizaje Alegre!*

\href{https://www.ps192.org}{www.ps192.org}
