#+title: Promotional Criteria And Grading Policy 2024
#+SUBTITLE: school leters to parents
#+AUTHOR: Hilduara Abreu
#+LaTeX_CLASS_OPTIONS: [letterpaper, 12pt]
#+EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil title:nil num:nil
#+LATEX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{manni}
#+LATEX_HEADER:\usepackage{pdfpages}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage[top=1.4in, left=0.5in, right=0.5in, bottom=0.8in]{geometry}
#+LATEX_HEADER:\usepackage[T1]{fontenc}
#+LATEX_HEADER:\usepackage{helvet}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER:\setlength{\parindent}{0em}
#+LATEX_HEADER:\setlength{\parskip}{1em}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage {color}
#+LATEX_HEADER:\usepackage {tabularray}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor=blue,
#+LATEX_HEADER:     filecolor=magenta,
#+LATEX_HEADER:     urlcolor=cyan,
#+LATEX_HEADER:     citecolor=green,
#+LATEX_HEADER:     pdfborder={0 0 0}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[most]{tcolorbox}

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\vspace*{0.01in}

\newtcolorbox{redbox}[1][]{
  colback=red!5!white,
  colframe=red!75!black,
  fonttitle=\bfseries,
  coltitle=black,
  enhanced,
  attach boxed title to top center={yshift=-2mm},
  title=#1,
  boxed title style={colback=red!50!white}
}
#+END_EXPORT

Date: [[https://www.ps192.org/apps/bbmessages/show_bbm.jsp?REC_ID=139439][September
5th, 2024]]

Subject: \textbf{Promotional Criteria and grading Policy 2024-25}

Dear Parents and Guardians,

Chancellor Regulation A-501 implements a system-wide promotion policy with clearly defined standards for
promotion for each grade. The P.S. 192 Promotional Criteria Policy provides the process and procedures
for the implementation of this promotion policy. This policy is effective as of September 5th, 2024.

This policy is being promulgated in the context of the following goals established by the Chancellor’s
Regulation A-501:

All students in Kindergarten through grade 5 will meet or exceed rigorous academic standards in a performance-based core curriculum. In grades 3 through 5, all students will meet or exceed the promotion standards referred to in this regulation, and set forth in DOE issued guidance, in order to be promoted to the next grade and, ultimately, to be prepared for college and careers.

- The entire school community will be engaged continuously in creating and supporting effective strategies for improved student achievement.
- A comprehensive student assessment system, aligned with established State and City performance standards, will be used on an ongoing basis to measure student progress and to improve classroom instruction.

#+begin_export latex
\begin{redbox}[Classwork Grading System]
\begin{table}[H]
\centering
\begin{tblr}{
  colspec={|X|X|},
  row{1}={font=\bfseries\color{MacaroniandCheese},c},
  hlines,
  vlines,
  hline{1,6} = {-}{0.08em},
}
\textbf{Component}              & \textbf{Weight} \\
In-House Assessments            & 50\%            \\
Daily Classwork                 & 30\%            \\
Classroom Participation         & 10\%            \\
Projects                        & 5\%             \\
Homework                        & 5\%             \\
\end{tblr}
\end{table}
\end{redbox}
#+end_export

*Promotional Criteria for Grades K-2*
- 95 percent Attendance
#+begin_export latex
\pagebreak
\vspace*{-1cm}
#+end_export
- Meet Performance Standards in ALL Core Subjects: ELA, Math, S.S., and Science. This means to
  obtain a Performance Level 2 (a numeric score of 65 percent) in all core subject areas: Reading,
  Writing, Mathematics, Science, and Social Studies. The average of the quizzes and unit exams will
  be used to determine the overall grade:
  - Level 1: An aggregate average score of 0-64 points
  - Level 2: An aggregate average score of 65-79 points
  - Level 3: An aggregate average score of 80-89 points
  - Level 4: An aggregate average score of 90-100 points

*Reading: Meet Minimum Grade Specific DRA Reading Benchmark*
- Kindergarten: Benchmark Reading Level 6 (E)
- First Grade: Benchmark Reading Level 15-16 (L)
- Second Grade: Benchmark Reading Level 18 (J)

*Writing: Obtain a cumulative Level 2 performance rating in the Writing Portfolio*
- Kindergarten: 4 Writing Pieces (2 fiction and 2 non-fiction)
- First grade: 4 Writing Performance Tasks (2 fiction and 2 non-fiction)
- Second grade: 4 Writing Performance Tasks (2 fiction and 2 non-fiction)

*Math: Obtain a cumulative Level 2 performance rating. The average of the quizzes and unit exams will be used to determine the overall grade.*
- Level 1: An aggregate average score of 0-64 points
- Level 2: An aggregate average score of 65-79 points
- Level 3: An aggregate average score of 80-89 points
- Level 4: An aggregate average score of 90-100 points

*Project Assignments: Obtain a cumulative Level 2 performance rating in each project.*
- Kindergarten: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)
#+begin_export latex
\pagebreak
\vspace*{-1cm}
#+end_export
- First grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)
- Second grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)

*Teacher’s Recommendation*
- Holistic analysis and evidence of classwork

*Promotional Criteria for Grades 3-5*
- 95 percent Attendance
- Meet Performance Standards in ALL Core Subjects: ELA, Math, S.S., and Science. This means to obtain a Performance Level 2 (a numeric score of 65 percent) in all core subject areas: Reading, Writing,

*Mathematics, Science, and Social Studies. The average of the quizzes and unit exams will be used to determine the overall grade:*
  - Level 1: An aggregate average of 0-64 points
  - Level 2: An aggregate average of 65-79 points
  - Level 3: An aggregate average of 80-89 points
  - Level 4: An aggregate average of 90-100 points

*Reading: Meet Minimum Grade Specific DRA Reading Benchmark*
- Third Grade: Benchmark Reading Level 34-38 (M-N)
- Fourth Grade: Benchmark Reading Level 38-40 (O-P)
- Fifth Grade: Benchmark Reading Level 50 (Q-R)

*Writing: Obtain a cumulative Level 2 performance rating in the Writing Portfolio*
- Third Grade: 4 Writing Pieces (2 fiction and 2 non-fiction)
- Fourth Grade: 4 Writing Performance Tasks (1 fiction and 3 non-fiction)
- Fifth Grade: 4 Writing Performance Tasks (1 fiction and 3 non-fiction)
#+begin_export latex
\pagebreak
\vspace*{-0.5cm}
#+end_export
*Math: Obtain a cumulative Level 2 performance rating. The average of the quizzes and unit exams will be used to determine the overall grade.*
- Level 1: An aggregate average score of 0-64 points
- Level 2: An aggregate average score of 65-79 points
- Level 3: An aggregate average score of 80-89 points
- Level 4: An aggregate average score of 90-100 points

*Project Assignments: Obtain a cumulative Level 2 performance rating in each project.*
- Third Grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)
- Fourth Grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)
- Fifth Grade: 3 Individual Projects (December – S.S.; Feb. – Math; Apr. – Science)

*Teacher's Recommendation*
- Holistic analysis and evidence of classwork

*Promotional Criteria for English Language Learners*

English Language Learners will be held to promotional standards based on the
number of years in NYC Public Schools:
- 1st year ELLs and SIFEs
  - Meet benchmarks in specific subject areas such as Math, S.S., and Science in
    their native language.
- 2nd and 3rd year ELLs
  - Score a level 2 in the NYS Math Assessment and make expected gains in the NYSESLAT (51 points within a proficiency level)
  - Score at least a score of 65 percent (Performance Level 2) in a minimum of
    three core subject areas.
#+begin_export latex
\pagebreak
\vspace*{-1cm}
#+end_export
- 4th year ELLs will be held to the same standards as English Language Proficient Students.

*Promotional Criteria for Special Education Students*
- Special Education students will be held to the promotion standards stated in the student’s IEP.
- A student whose IEP does not specify modified promotion criteria will be held to the same standard promotional criteria as General Education Students.
- Teachers will use all available assessments: standardized tests, performance tasks, ongoing assessments of student work, conference notes, teacher observations, and professional judgment – as a mechanism to improve classroom instruction and to provide parents with detailed information about their child’s academic progress.

All promotional criteria are subject to the Principal’s final approval. Parents will also be involved in the decision-making process. Teachers will maintain collections of students' work and formative and summative data that document students' progress toward meeting performance standards and benchmarks. Teachers will be meeting with parents regularly for:
- Our staff shall employ various communication methods to ensure parents and guardians are consistently informed about their child’s social-emotional and academic development.
  - Zoom or Google virtual conferences
  - Phone conversations
  - Written communication, which includes ClassDojo, email, and text messages, will be utilized to inform parents.

In Unity,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

\textbf{Hilduara Abreu}, \textbf{Principal}

\textit{The School of Joyful Learning!}

[[https://www.ps192.org][www.ps192.org]]
