#+TITLE: School Year 2024-25 | Principal Message January 2025
#+AUTHOR: Hilduara Abreu
#+EMAIL: ps192@ps192.org
#+LaTeX_CLASS_OPTIONS: [letterpaper, 14pt]
#+EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil title:nil num:nil
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usemintedstyle{manni}
#+LATEX_HEADER: \usepackage{pdfpages}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage[top=1.4in, left=0.5in, right=0.5in, bottom=0.8in]{geometry}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{helvet}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0pt}
#+LATEX_HEADER: \setlength{\parindent}{0em}
#+LATEX_HEADER: \setlength{\parskip}{1em}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage {color}
#+LATEX_HEADER: \usepackage {tabularray}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor=blue,
#+LATEX_HEADER:     filecolor=magenta,
#+LATEX_HEADER:     urlcolor=cyan,
#+LATEX_HEADER:     citecolor=green,
#+LATEX_HEADER:     pdfborder={0 0 0}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage[most]{tcolorbox}

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\newpage
#+END_EXPORT
\vspace*{-0.2cm}
/*Subject: Welcome to January, 2025 at PS 192: The School of Joyful Learning!*/

Dear PS192 Families,

Happy New Year!

I extend my warmest wishes for a healthy, peaceful, and successful start to 2025. At P.S. 192, we firmly believe that learning is a collaborative effort between home and school. I sincerely thank you for your continued dedication and involvement in your child’s education.

The start of a new year presents an excellent opportunity to embrace new habits and set meaningful goals that can enhance both your life and your child’s academic journey. It is also a time to reflect on areas where growth and improvement are possible.

We have an exciting month ahead, filled with opportunities for learning and engagement. I encourage you to participate in the upcoming events:

Parent Association Meeting
   - Date: January 14
   - Time: 8:00 a.m.
   - Location: Library

School Leadership Team (SLT) Meeting
   - Date: January 22
   - Time: 2:30 p.m. to 5:30 p.m.

Coffee with the Principal
   - Date: January 31
   - Time: 8:00 a.m.
   - Location: Library

I look forward to seeing you at this month’s events and continuing our partnership to support student success.

With Justice, Honor, and Self-Discipline,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

*The School of Joyful Learning!*

\href{www.ps192.org}{www.ps192.org}

\newpage

#+BEGIN_EXPORT latex
\fancyfoot[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.8,-0.5){\includegraphics[width=8.8in,height=1.3in]{logo-1}}\end{picture}}
\fancyhead[C]{\setlength{\unitlength}{1in}\begin{picture}(5,0)\put(-1.9,-0.5){\includegraphics[width=8.9in,height=1.3in]{logo-2}}\end{picture}}
\fancyhead[R]{\thepage}
\pagenumbering{gobble}

\begin{document}
\newpage
#+END_EXPORT
\vspace*{-0.2cm}

/*Asunto: Bienvenidos a enero de 2025 en PS 192: ¡La Escuela del Aprendizaje Alegre!*/

*Estimados padres y tutores*,

¡Feliz Año Nuevo!

Les extiendo mis más cálidos deseos para un comienzo saludable, pacífico y exitoso en el 2025. En la P.S. 192, creemos firmemente que el aprendizaje es un esfuerzo colaborativo entre el hogar y la escuela. Les agradezco sinceramente por su continuo compromiso e involucramiento en la educación de su hijo/a.

El inicio de un nuevo año presenta una excelente oportunidad para adoptar nuevos hábitos y establecer metas significativas que puedan mejorar tanto su vida como el trayecto académico de su hijo/a. También es un momento para reflexionar sobre las áreas donde se puede crecer y mejorar.

Tenemos un mes emocionante por delante, lleno de oportunidades para aprender y participar. Les animo a participar en los próximos eventos:

Reunión de la Asociación de Padres
   - Fecha: 14 de enero
   - Hora: 8:00 a.m.
   - Ubicación: Biblioteca

Reunión del Equipo de Liderazgo Escolar (SLT)
   - Fecha: 22 de enero
   - Hora: 2:30 p.m. a 5:30 p.m.

Café con la Directora
   - Fecha: 31 de enero
   - Hora: 8:00 a.m.
   - Ubicación: Biblioteca

Espero verlos en los eventos de este mes y continuar nuestra colaboración para apoyar el éxito de los estudiantes.

Con justicia, honor y autodisciplina,

#+BEGIN_EXPORT latex
\includegraphics[width=0.2\textwidth]{hil_signature}
#+END_EXPORT

*Hilduara Abreu, Principal*

La escuela del aprendizaje allegro!

\href{www.ps192.org}{www.ps192.org}
